from kb import KnowledgeBase, Triplet
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy


# all-MiniLM-L6-v2 es un modelo de Microsoft alojado en HuggingFace que es el estándar para tareas de comparación de frases por su equilibrio entre velocidad y precisión. 
# Es gratuito bajo licencia Apache 2.0.
MODEL = 'all-MiniLM-L6-v2'  # Modelo ligero y gratuito (aprox 80MB)


class KnowledgeComparator:

    TRANSFORMER_LANGUAGE_MODEL = 'all-MiniLM-L6-v2'  # Modelo ligero y gratuito (aprox 80MB)
    
    def __init__(self, ground_truth_kb: KnowledgeBase, llm_kb: KnowledgeBase) -> None:
        self.ground_truth_kb = ground_truth_kb
        self.llm_kb = llm_kb
        self.language_model = SentenceTransformer(self.TRANSFORMER_LANGUAGE_MODEL)

    def compare(self, threshold: float = 0.85) -> list[tuple[Triplet, Triplet, float]]:
        """Compare the triplets in this knowledge base with those in another knowledge base and return a list of tuples containing the compared triplets and their similarity score.
        
        This method uses a Semantic Similarity Matrix approach, where each triplet is converted into a sentence and then into an embedding vector. 
        The similarity between the triplets is computed using cosine similarity of their embeddings. 
        This allows for a more robust comparison that can capture semantic similarities even when the wording is different.
        """
        this_sentences = [triplet.to_sentence() for triplet in self.ground_truth_kb.triplets]
        other_sentences = [triplet.to_sentence() for triplet in self.llm_kb.triplets]
        this_vecs = self.language_model.encode(this_sentences)
        other_vecs = self.language_model.encode(other_sentences)

        similarity_matrix = cosine_similarity(this_vecs, other_vecs)

        results = []
        # Para controlar qué tripletas del LLM ya han sido "usadas"
        used_llm_indices = set()

        for i, row in enumerate(similarity_matrix):
            best_match_idx = numpy.argmax(row)
            best_score = row[best_match_idx]
            
            if best_score >= threshold:
                # Marcamos que esta tripleta del LLM es válida
                is_first_time_used = best_match_idx not in used_llm_indices
                used_llm_indices.add(best_match_idx)
                
                results.append({
                    "real": self.ground_truth_kb.triplets[i],
                    "llm": self.llm_kb.triplets[best_match_idx],
                    "score": best_score,
                    "match": True,
                    "llm_index": best_match_idx, # Guardamos el índice para deduplicar luego
                    "is_unique_hit": is_first_time_used # Flag clave para Precision
                })
            else:
                results.append({
                    "real": self.ground_truth_kb.triplets[i],
                    "match": False
                })
        return results
    

    def calculate_precision(self, batch_results: list[tuple[Triplet, Triplet, float]]) -> float:
        """Precision: From all the triplets generated by the LLM, what percentage is correct (true)?
        It measures the fidelity and lack of hallucinations.
        
        Precision = Correctly Matched Triplets / Total LLM-Generated Triplets
        """
        total_llm_triples = len(self.llm_kb.triplets)
        if total_llm_triples == 0:
            return 0.0
        
        # Count how many of the LLM-generated triplets had a match
        unique_matches = sum(1 for res in batch_results if res.get("match") and res.get("is_unique_hit"))        
        precision = unique_matches / total_llm_triples
        return precision

    def calculate_recall(self, batch_results: list[tuple[Triplet, Triplet, float]]) -> float:
        """Recall: Of all the knowledge that exists in the ground truth, how much did the LLM retrieve?
        It measures the coverage or "% of knowledge retrieved".

        Recall = Correctly Matched Triplets / Total Triplets in the Ground Truth
        """
        total_triples_in_ground_truth = len(self.ground_truth_kb.triplets)
        if total_triples_in_ground_truth == 0:
            return 0.0
        
        # Count how many of the ground truth triplets were found by the LLM
        matches = sum(1 for res in batch_results if res.get("match") is True)
        
        recall = matches / total_triples_in_ground_truth
        return float(recall)

    def calculate_f1_score(self, precision: float, recall: float) -> float:
        """F1 Score: The harmonic mean of precision and recall, providing a single metric that balances both aspects of performance.

        F1 Score = 2 * (Precision * Recall) / (Precision + Recall)
        """
        if precision + recall == 0:
            return 0.0
        
        f1_score = 2 * (precision * recall) / (precision + recall)
        return f1_score
    
    def calculate_hallucination_rate(self, batch_results: list[dict]) -> float:
        """
        Devuelve el % de tripletas que el LLM generó pero que no 
        tienen sustento en el Ground Truth.
        """
        return 1.0 - self.calculate_precision(batch_results)

    def get_hallucinations(self, batch_results: list[dict]) -> list[Triplet]:
        """
        Retorna la lista de tripletas que el LLM 'alucinó' 
        (las que no hicieron match con nada del GT).
        """
        # 1. Obtenemos los índices de las tripletas del LLM que sí fueron correctas
        matched_indices = {res["llm_index"] for res in batch_results if res.get("match")}
        
        # 2. Las alucinaciones son todas las que NO están en ese conjunto de índices
        hallucinations = [
            triplet for i, triplet in enumerate(self.llm_kb.triplets)
            if i not in matched_indices
        ]
        
        return hallucinations